name: Build and Deploy application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'
      
    - name: Build .Net
      run: dotnet build --configuration release

    - name: Execute Tests
      run: dotnet test --configuration release

    - name: Execute nuget package
      run: dotnet pack --configuration release

    - name: Push do nuget a
      run: dotnet nuget push "bin/Release/*.nupkg" -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/leandrolevv/index.json