name: Build and Deploy application

on:
  push:
    branch:
      -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    

    - name: Push do nuget
      run: dotnet nuget push "/MoneyExtension/bin/Release/*.nupkg" -k {{secrets.NUGET_MONEYEXTENSION_TOKEN}} -s https://api.nuget.org/v3/index.json