name: Build and Deploy application

on:
  push:
    branch:
      -main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main

    - name: Set Up .Net
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '7.0.0'
      
    - name: Build .Net
      run: dotnet build --configuration release

    - name: Execute Tests
      run: dotnet test --configuration release

    - name: Execute nuget package
      run: dotnet pack --configuration release

    - name: Push do nuget
      run: dotnet nuget push "MoneyExtension/bin/release/*.nupkg" -k {{ secrets.NUGET_MONEYEXTENSION_TOKEN }} -s https://api.nuget.org/v3/index.json